Call `super` `initialize` for Ruby HEAD compatibility
ruby/logger#85 added `@level_override` to the `Logger` initializer.

Since we didn't call `super` in `initialize`, the variable was
uninitialized, and we would run into a `NoMethodError` in `Logger#level`
on Ruby HEAD:

    def level
      @level_override[Fiber.current] || @level
      #              ^^^^^^^^^^^^^^^ NoMethodError: undefined method `[]' for nil:NilClass
    end